#!/usr/bin/env bash

current_dir="$(pwd)"
last_link="$1";
video_name="$(
  printf "${last_link}" |
    sed -r "s/.*\/\/([^\/]*\/){3}([^\/]*)\/.*/\2/" - 
  )"
declare -i last_no=$(
  printf "${last_link}" | 
    sed "s/.*\/\([0-9]\{1,4\}\).ts$/\1/" - 
  )

(
cd "${current_dir}"
mkdir "${video_name}.tmp" && cd $_
# create list of links by replacing last no
# like https://blabla/file/name/$last_no.ts
for (( i=0; i<="${last_no}"; i++ ));do
  printf "${last_link}" |
    sed "s/\(.*\/\)\([0-9]\{1,4\}\)\(.ts$\)/\1$i\3\n/" - >> links 
done

cat links | 
    # run in paralled 20 instances of wget
    xargs -I '{}' -P 20 wget -nvc '{}'

for i in `ls *.ts | sort -V`;do
echo "file $i";
done >> filelist

ffmpeg -f concat -i filelist -c copy -bsf:a aac_adtstoasc "${video_name}.mp4"

mv "${video_name}.mp4" ../
)

