#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "No link provided" >&2
  exit 1
fi

last_link="$1";

video_name="$(
  printf "${last_link}" |
    sed -r "s/.*\/\/([^\/]*\/){3}([^\/]*)\/.*/\2/" - 
  )"

#video_version="$(
#  printf "${last_link}" |
#    sed -r "s/.*\/\/([^\/]*\/){4}([^\/]*)\/.*/\2/" -
#  )"

declare -i last_no="$(
  printf "${last_link}" | 
    sed "s/.*\/\([0-9]\{1,4\}\).ts$/\1/" - 
  )"

mkdir ".${video_name}.tmp" && cd $_

# create list of links by replacing last no
# like https://blabla/file/name/$last_no.ts
for (( i=0; i<="${last_no}"; i++ ));do
  printf "${last_link}" |
    sed "s/\(.*\/\)\([0-9]\{1,4\}\)\(.ts$\)/\1$i\3\n/" - >> links 
done

cat links | 
    # run in paralled 20 instances of wget
    xargs -I '{}' -P 20 wget -nvc '{}'

# construct list of sorted files suitable for ffmpeg concat
# one row of filelist is like: file vid1.ts
echo "$(ls *.ts -1v)" | sed -r "s/^/file /" - > filelist

ffmpeg -f concat -i filelist -c copy -bsf:a aac_adtstoasc "${video_name}.mp4"

mv "${video_name}.mp4" ../

