#!/bin/bash

w_acrobat() {
  w_acrobat_path='C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe'
  lin_acrobat_path="$(wslpath "${w_acrobat_path}")"
  w_file_path="$(wslpath -w "$1")"
  ("${lin_acrobat_path}" "${w_file_path}" & )
}

w_sumatrapdf() {
  w_sumatrapdf_path='C:\Program Files\SumatraPDF\SumatraPDF.exe'
  wsl_path="$(wslpath "${w_sumatrapdf_path}")"
  w_file_path="$(wslpath -w "$1")"
  ("${wsl_path}" "${w_file_path}" &)
}
w_sumatrapdf() {
  w_file_path="$(wslpath -w "$1")"
  (cmd.exe /c start "" "SumatraPDF.exe" "${w_file_path}" &) > /dev/null 2>&1
}

w_libreoffice() {
  w_libreoffice_path='C:\Program Files\LibreOffice\program\soffice.exe'
  wsl_path="$(wslpath "${w_libreoffice_path}")"
  w_file_path="$(wslpath -w "$1")"
  ("${wsl_path}" "${w_file_path}" &)
}

w_vlc() {
  w_vlc_path='C:\Program Files\VideoLAN\VLC\vlc.exe'
  lin_vlc="$(wslpath "$w_vlc_path")"
  ("${lin_vlc}" "$1" & ) > /dev/null 2>&1 
}

w_edge() {
  w_edge_path='C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'
  lin_edge="$(wslpath "${w_edge_path}")"
  w_file="$(wslpath -w "$1")"
  "${lin_edge}" "${w_file}"
}

#####################################################
# if no arguments, read from stdin, otherwise arg1
(( $# == 0 )) && filepath="$(cat)" || filepath="$1"

# get extension from filename
ext="$(echo "${filepath}" | sed -r "s/^.+\.//" -)"
[[ "${ext}" == "mhtml" ]] && w_edge "${filepath}"
[[ "${ext}" == "html" ]] && w_edge "${filepath}"
[[ "${ext}" == "mp4" ]] && w_vlc "${filepath}"
# [[ "${ext}" == "pdf" ]] && w_sumatrapdf "${filepath}"
[[ "${ext}" == "pdf" ]] && w_acrobat "${filepath}"
[[ "${ext}" == "epub" ]] && w_sumatrapdf "${filepath}"
[[ "${ext}" == "ods" ]] && w_libreoffice "${filepath}"
