#!/usr/bin/env bash

declare -i i=0;
mapfile -t list < <(ls -v -w 0);
for n in "${list[@]}";do
  ren="$(echo "${n}" | sed -r "s/[0-9.]*\.(.*)/${i}\.\1/" -)"
  (( i =i+ 1 ))
  mv -iv "${n}" "${ren}"
done 
